name: notification_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  flutter_local_notifications: ^6.0.0
  hooks_riverpod: ^0.14.0+4
  dartz: ^0.10.0-nullsafety.2
  easy_localization: ^3.0.0
  flex_color_scheme: ^2.1.1
  expandable: ^5.0.1
  flutter_background: ^1.0.0
  flutter_downloader: ^1.6.1
  flutter_funding_choices: ^0.2.0
  flutter_hooks: ^0.17.0
  flutter_inappwebview: ^5.3.2
  font_awesome_flutter: ^9.0.0
  google_mobile_ads: ^0.13.0
  freezed: ^0.14.2
  google_fonts: ^2.1.0
  logger: ^1.0.0
  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  readmore: ^2.1.0
  sentry_flutter: ^5.1.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  permission_handler: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
